/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package market2.Paneles;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import market2.Classes.Ajustes.ajustes_Edit_date;
import market2.Classes.Ajustes.ajustes_horarios;
import market2.Classes.Forms_state;
import market2.Classes.Fun_BTObuscar;
import market2.Classes.Fun_BTOmodificar;
import market2.Forms.Edit_date;

/**
 *
 * @author Usuario
 */
public class Panel_horarios extends javax.swing.JPanel {
    //Forms_state state = new Forms_state();
     private ajustes_Edit_date edit_date = new ajustes_Edit_date();

    /**
     * Creates new form Panel_Horarios
     */
    public Panel_horarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PM_horarios = new javax.swing.JPopupMenu();
        IM_modificar = new javax.swing.JMenuItem();
        PANEL_set = new javax.swing.JPanel();
        CB_list_horarios = new javax.swing.JComboBox<>();
        TXT_busqueda_horarios = new javax.swing.JTextField();
        BTO_buscar_horarios = new javax.swing.JButton();
        PANEL_get = new javax.swing.JPanel();
        PANEL_JS = new javax.swing.JScrollPane();
        JT_horarios = new javax.swing.JTable();

        PM_horarios.setToolTipText("");
        PM_horarios.setBorder(null);
        PM_horarios.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                PM_horariosPopupMenuWillBecomeVisible(evt);
            }
        });

        IM_modificar.setText("Modificar");
        IM_modificar.setBorder(null);
        IM_modificar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IM_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        IM_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IM_modificarMouseClicked(evt);
            }
        });
        IM_modificar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                IM_modificarComponentShown(evt);
            }
        });
        IM_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IM_modificarActionPerformed(evt);
            }
        });
        PM_horarios.add(IM_modificar);

        setBackground(new java.awt.Color(153, 153, 0));

        PANEL_set.setBackground(new java.awt.Color(51, 51, 51));

        CB_list_horarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ci", "Lastname", "Tipo" }));

        TXT_busqueda_horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_busqueda_horariosActionPerformed(evt);
            }
        });

        BTO_buscar_horarios.setText("Buscar");
        BTO_buscar_horarios.setToolTipText("");
        BTO_buscar_horarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTO_buscar_horariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PANEL_setLayout = new javax.swing.GroupLayout(PANEL_set);
        PANEL_set.setLayout(PANEL_setLayout);
        PANEL_setLayout.setHorizontalGroup(
            PANEL_setLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_setLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(CB_list_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXT_busqueda_horarios)
                .addGap(18, 18, 18)
                .addComponent(BTO_buscar_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(603, 603, 603))
        );
        PANEL_setLayout.setVerticalGroup(
            PANEL_setLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_setLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANEL_setLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BTO_buscar_horarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PANEL_setLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CB_list_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXT_busqueda_horarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        PANEL_get.setBackground(new java.awt.Color(255, 51, 0));
        PANEL_get.setLayout(new java.awt.GridLayout(1, 0));

        PANEL_JS.setBackground(new java.awt.Color(51, 51, 51));
        PANEL_JS.setForeground(new java.awt.Color(255, 255, 255));

        JT_horarios.setBackground(new java.awt.Color(255, 255, 255));
        JT_horarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        JT_horarios.setForeground(new java.awt.Color(51, 51, 51));
        JT_horarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ci", "Lastname", "lun", "mar", "mie", "jue", "vie", "sab", "dom"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JT_horarios.setComponentPopupMenu(PM_horarios);
        JT_horarios.setFillsViewportHeight(true);
        JT_horarios.setFocusable(false);
        JT_horarios.setGridColor(new java.awt.Color(153, 153, 153));
        JT_horarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JT_horariosMouseMoved(evt);
            }
        });
        JT_horarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_horariosMouseClicked(evt);
            }
        });
        PANEL_JS.setViewportView(JT_horarios);

        PANEL_get.add(PANEL_JS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PANEL_get, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PANEL_set, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PANEL_set, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(PANEL_get, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTO_buscar_horariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTO_buscar_horariosActionPerformed
       
       Fun_BTObuscar instancia = new Fun_BTObuscar(this.JT_horarios,this.TXT_busqueda_horarios.getText(),this.CB_list_horarios.getSelectedItem().toString());
    
       try {
            instancia.additemtotable_busqueda(1,instancia.filtrar(instancia.consulta_panel_horarios()));
       } catch (SQLException ex) {
            Logger.getLogger(Panel_gestion_de_usuarios.class.getName()).log(Level.SEVERE, null, ex);
       }
        
       repaint();    
        
        
    }//GEN-LAST:event_BTO_buscar_horariosActionPerformed

    private void TXT_busqueda_horariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_busqueda_horariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_busqueda_horariosActionPerformed

    private void JT_horariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_horariosMouseClicked
 
        
    }//GEN-LAST:event_JT_horariosMouseClicked

    private void IM_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IM_modificarActionPerformed
        Fun_BTOmodificar instancia = new Fun_BTOmodificar(this.JT_horarios,null);

         System.out.println(instancia.columna_valida());
         if(instancia.columna_valida()==true){
            //state.state_ajustes_Edit_date(true);  
            edit_date.show(true);
        }
        
        
    }//GEN-LAST:event_IM_modificarActionPerformed

    private void JT_horariosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_horariosMouseMoved
    }//GEN-LAST:event_JT_horariosMouseMoved

    private void IM_modificarComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_IM_modificarComponentShown

    }//GEN-LAST:event_IM_modificarComponentShown

    private void PM_horariosPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_PM_horariosPopupMenuWillBecomeVisible
       // state.state_ajustes_Edit_date(false);    
            edit_date.show(false);

        Fun_BTOmodificar instancia = new Fun_BTOmodificar(this.JT_horarios,this.JT_horarios.getMousePosition());
            instancia.setCI(instancia.capturaCI(JT_horarios));
            instancia.setColumna(instancia.capturarColumna(JT_horarios));
            System.out.println(this.JT_horarios.getMousePosition());

            
    }//GEN-LAST:event_PM_horariosPopupMenuWillBecomeVisible

    private void IM_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IM_modificarMouseClicked

    }//GEN-LAST:event_IM_modificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTO_buscar_horarios;
    public javax.swing.JComboBox<String> CB_list_horarios;
    public javax.swing.JMenuItem IM_modificar;
    public javax.swing.JTable JT_horarios;
    public javax.swing.JScrollPane PANEL_JS;
    public javax.swing.JPanel PANEL_get;
    public javax.swing.JPanel PANEL_set;
    public javax.swing.JPopupMenu PM_horarios;
    public javax.swing.JTextField TXT_busqueda_horarios;
    // End of variables declaration//GEN-END:variables
}
