

package market2.Forms;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import market2.Classes.Ajustes.ajustes_form_admin;
import market2.Classes.Ajustes.ajustes_gestion_usuarios;
import market2.Classes.Ajustes.ajustes_horarios;
import market2.Classes.Fun_BTObuscar;
import market2.Classes.Gestor_Paneles;
import market2.Classes.admin_form_dimensiones;
import market2.Paneles.Panel_gestion_de_usuarios;

public class main_form_admin extends javax.swing.JFrame {
/*public static ajustes_gestion_usuarios gestion_usuarios = new ajustes_gestion_usuarios();
public static ajustes_horarios horarios = new ajustes_horarios();*/
public Gestor_Paneles paneles_state = new Gestor_Paneles();
private admin_form_dimensiones dimension = new admin_form_dimensiones();

//public static ajustes_form_admin size = new ajustes_form_admin();

    /** Creates new form main_form_admi */
    public main_form_admin() {
        initComponents();    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_form_admin_barra_superior = new javax.swing.JPanel();
        bto_form_admin_cerrar = new javax.swing.JButton();
        panel_form_admin_barra_tareas = new javax.swing.JPanel();
        panel_form_admin_horariosusu = new javax.swing.JPanel();
        bto_form_admin_horariosusu = new javax.swing.JButton();
        PANEL_softwareAlmacen = new javax.swing.JPanel();
        BTO_softwareAlmacen = new javax.swing.JButton();
        PANEL_perfil = new javax.swing.JPanel();
        BTO_perfil = new javax.swing.JButton();
        PANEL_gestionUsuarios = new javax.swing.JPanel();
        BTO_gestionUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_form_admin_barra_superior.setBackground(new java.awt.Color(0, 41, 57));
        panel_form_admin_barra_superior.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        bto_form_admin_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bto_form_admin_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/market2/imagenes/window-close.png"))); // NOI18N
        bto_form_admin_cerrar.setBorder(null);
        bto_form_admin_cerrar.setBorderPainted(false);
        bto_form_admin_cerrar.setContentAreaFilled(false);
        bto_form_admin_cerrar.setFocusPainted(false);
        bto_form_admin_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto_form_admin_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bto_form_admin_cerrarMouseEntered(evt);
            }
        });
        bto_form_admin_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_form_admin_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_form_admin_barra_superiorLayout = new javax.swing.GroupLayout(panel_form_admin_barra_superior);
        panel_form_admin_barra_superior.setLayout(panel_form_admin_barra_superiorLayout);
        panel_form_admin_barra_superiorLayout.setHorizontalGroup(
            panel_form_admin_barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_form_admin_barra_superiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bto_form_admin_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_form_admin_barra_superiorLayout.setVerticalGroup(
            panel_form_admin_barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bto_form_admin_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_form_admin_barra_tareas.setBackground(new java.awt.Color(51, 51, 51));

        panel_form_admin_horariosusu.setLayout(new java.awt.GridLayout(1, 0));

        bto_form_admin_horariosusu.setBackground(new java.awt.Color(255, 255, 255));
        bto_form_admin_horariosusu.setForeground(new java.awt.Color(255, 255, 255));
        bto_form_admin_horariosusu.setText("Gestion de horarios");
        bto_form_admin_horariosusu.setToolTipText("");
        bto_form_admin_horariosusu.setBorder(null);
        bto_form_admin_horariosusu.setBorderPainted(false);
        bto_form_admin_horariosusu.setContentAreaFilled(false);
        bto_form_admin_horariosusu.setFocusPainted(false);
        bto_form_admin_horariosusu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bto_form_admin_horariosusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bto_form_admin_horariosusuActionPerformed(evt);
            }
        });
        panel_form_admin_horariosusu.add(bto_form_admin_horariosusu);

        PANEL_softwareAlmacen.setLayout(new java.awt.GridLayout(1, 0));

        BTO_softwareAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        BTO_softwareAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        BTO_softwareAlmacen.setText("Software de Almacen");
        BTO_softwareAlmacen.setBorder(null);
        BTO_softwareAlmacen.setContentAreaFilled(false);
        BTO_softwareAlmacen.setFocusPainted(false);
        BTO_softwareAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTO_softwareAlmacenActionPerformed(evt);
            }
        });
        PANEL_softwareAlmacen.add(BTO_softwareAlmacen);

        PANEL_perfil.setLayout(new java.awt.GridLayout(1, 0));

        BTO_perfil.setBackground(new java.awt.Color(255, 255, 255));
        BTO_perfil.setForeground(new java.awt.Color(255, 255, 255));
        BTO_perfil.setText("Perfil");
        BTO_perfil.setBorder(null);
        BTO_perfil.setContentAreaFilled(false);
        BTO_perfil.setFocusPainted(false);
        BTO_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTO_perfilActionPerformed(evt);
            }
        });
        PANEL_perfil.add(BTO_perfil);

        PANEL_gestionUsuarios.setLayout(new java.awt.GridLayout(1, 0));

        BTO_gestionUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        BTO_gestionUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        BTO_gestionUsuarios.setText("Gestion de usuarios");
        BTO_gestionUsuarios.setBorder(null);
        BTO_gestionUsuarios.setContentAreaFilled(false);
        BTO_gestionUsuarios.setFocusPainted(false);
        BTO_gestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTO_gestionUsuariosActionPerformed(evt);
            }
        });
        PANEL_gestionUsuarios.add(BTO_gestionUsuarios);

        javax.swing.GroupLayout panel_form_admin_barra_tareasLayout = new javax.swing.GroupLayout(panel_form_admin_barra_tareas);
        panel_form_admin_barra_tareas.setLayout(panel_form_admin_barra_tareasLayout);
        panel_form_admin_barra_tareasLayout.setHorizontalGroup(
            panel_form_admin_barra_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_form_admin_barra_tareasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_form_admin_barra_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PANEL_gestionUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PANEL_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PANEL_softwareAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(panel_form_admin_barra_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_form_admin_barra_tareasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel_form_admin_horariosusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_form_admin_barra_tareasLayout.setVerticalGroup(
            panel_form_admin_barra_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_form_admin_barra_tareasLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(PANEL_softwareAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(PANEL_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PANEL_gestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 176, Short.MAX_VALUE))
            .addGroup(panel_form_admin_barra_tareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_form_admin_barra_tareasLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(panel_form_admin_horariosusu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(447, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_form_admin_barra_superior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_form_admin_barra_tareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(862, 862, 862))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_form_admin_barra_superior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_form_admin_barra_tareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bto_form_admin_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_form_admin_cerrarActionPerformed
    System.exit(0);  

    }//GEN-LAST:event_bto_form_admin_cerrarActionPerformed

    private void bto_form_admin_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_form_admin_cerrarMouseClicked
    }//GEN-LAST:event_bto_form_admin_cerrarMouseClicked

    private void bto_form_admin_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto_form_admin_cerrarMouseEntered
    }//GEN-LAST:event_bto_form_admin_cerrarMouseEntered

    private void bto_form_admin_horariosusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bto_form_admin_horariosusuActionPerformed
   
     paneles_state.get_GestorUsuarios().show(false);
     paneles_state.get_GestorHorarios().show(true);
     
     paneles_state.get_GestorHorarios().setLocation(dimension.getX_barra_tareas(), dimension.getY_barra_superiro());  
    
      Fun_BTObuscar instancia = new Fun_BTObuscar( paneles_state.get_GestorHorarios().JT_horarios, paneles_state.get_GestorHorarios().TXT_busqueda_horarios.getText(), paneles_state.get_GestorHorarios().CB_list_horarios.getSelectedItem().toString());
    
    try {
            instancia.additemtotable_busqueda(1,instancia.filtrar(instancia.carga_usuarios_horarios()));
    } catch (SQLException ex) {
        Logger.getLogger(main_form_admin.class.getName()).log(Level.SEVERE, null, ex);
    }
                        
     this.repaint();    }//GEN-LAST:event_bto_form_admin_horariosusuActionPerformed

    private void BTO_softwareAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTO_softwareAlmacenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTO_softwareAlmacenActionPerformed

    private void BTO_gestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTO_gestionUsuariosActionPerformed
   
     paneles_state.get_GestorHorarios().show(false);
     paneles_state.get_GestorUsuarios().show(true);
    
     paneles_state.get_GestorUsuarios().setLocation(dimension.getX_barra_tareas(),dimension.getY_barra_superiro());  
      Fun_BTObuscar instancia = new Fun_BTObuscar( paneles_state.get_GestorUsuarios().JT_usuarios, paneles_state.get_GestorUsuarios().txt_buscar.getText(), paneles_state.get_GestorUsuarios().CB_lista.getSelectedItem().toString());
    
    try {
            instancia.additemtotable_busqueda(0,instancia.filtrar(instancia.carga_usuarios_busqueda()));
        
    } catch (SQLException ex) {
        Logger.getLogger(main_form_admin.class.getName()).log(Level.SEVERE, null, ex);
    }
                        
     this.repaint();    }//GEN-LAST:event_BTO_gestionUsuariosActionPerformed

    private void BTO_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTO_perfilActionPerformed
     
    }//GEN-LAST:event_BTO_perfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_form_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_form_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_form_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_form_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_form_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTO_gestionUsuarios;
    public javax.swing.JButton BTO_perfil;
    public javax.swing.JButton BTO_softwareAlmacen;
    public javax.swing.JPanel PANEL_gestionUsuarios;
    public javax.swing.JPanel PANEL_perfil;
    public javax.swing.JPanel PANEL_softwareAlmacen;
    public javax.swing.JButton bto_form_admin_cerrar;
    public javax.swing.JButton bto_form_admin_horariosusu;
    public javax.swing.JPanel panel_form_admin_barra_superior;
    public javax.swing.JPanel panel_form_admin_barra_tareas;
    public javax.swing.JPanel panel_form_admin_horariosusu;
    // End of variables declaration//GEN-END:variables

}
//k
//Panel buscar
/*
 horarios.show(false);
     busqueda.show(true);
     this.add(busqueda);
     this.busqueda.setLocation(size.x_barra_tareas, size.y_barra_superiro);  
    
      Fun_BTObuscar instancia = new Fun_BTObuscar(this.busqueda.JT_usuarios,this.busqueda.txt_buscar.getText(),this.busqueda.CB_lista.getSelectedItem().toString());
    
    try {
            instancia.additemtotable_busqueda(0,instancia.filtrar(instancia.carga_usuarios_busqueda()));
        
    } catch (SQLException ex) {
        Logger.getLogger(main_form_admin.class.getName()).log(Level.SEVERE, null, ex);
    }
                        
     this.repaint();
*/